export const COUNTRY_COLORS: Record<string, { primary: string; secondary: string; text: string }> = {
  ARG: { primary: "#75AADB", secondary: "#FFFFFF", text: "#000000" },
  BRA: { primary: "#009739", secondary: "#FEDD00", text: "#FFFFFF" },
  COL: { primary: "#FCD116", secondary: "#003893", text: "#000000" },
  MEX: { primary: "#006847", secondary: "#FFFFFF", text: "#FFFFFF" },
  USA: { primary: "#002868", secondary: "#BF0A30", text: "#FFFFFF" },
  CAN: { primary: "#FF0000", secondary: "#FFFFFF", text: "#FFFFFF" },
  URU: { primary: "#0081C4", secondary: "#FFFFFF", text: "#000000" },
  FRA: { primary: "#002395", secondary: "#ED2939", text: "#FFFFFF" },
  ESP: { primary: "#AA151B", secondary: "#F1BF00", text: "#FFFFFF" },
  GER: { primary: "#000000", secondary: "#DD0000", text: "#FFFFFF" },
  ENG: { primary: "#FFFFFF", secondary: "#CE1126", text: "#000000" },
  ITA: { primary: "#009246", secondary: "#FFFFFF", text: "#FFFFFF" },
  NED: { primary: "#F36C21", secondary: "#FFFFFF", text: "#FFFFFF" },
  POR: { primary: "#046A38", secondary: "#DA291C", text: "#FFFFFF" },
  BEL: { primary: "#000000", secondary: "#FFCD00", text: "#FFFFFF" },
  CRO: { primary: "#FF0000", secondary: "#FFFFFF", text: "#FFFFFF" },
  MAR: { primary: "#C1272D", secondary: "#006233", text: "#FFFFFF" },
  JPN: { primary: "#FFFFFF", secondary: "#BC002D", text: "#000000" },
  SEN: { primary: "#118833", secondary: "#FCD116", text: "#FFFFFF" },
  KOR: { primary: "#FFFFFF", secondary: "#CD2E3A", text: "#000000" },
  AUS: { primary: "#000031", secondary: "#FFFFFF", text: "#FFFFFF" },
  SUI: { primary: "#FF0000", secondary: "#FFFFFF", text: "#FFFFFF" },
  TUR: { primary: "#E30A17", secondary: "#FFFFFF", text: "#FFFFFF" },
  AUT: { primary: "#ED2939", secondary: "#FFFFFF", text: "#FFFFFF" },
  EGY: { primary: "#C1272D", secondary: "#000000", text: "#FFFFFF" },
  CIV: { primary: "#FF8200", secondary: "#FFFFFF", text: "#FFFFFF" },
  GHA: { primary: "#EF3340", secondary: "#FFCD00", text: "#FFFFFF" },
  TUN: { primary: "#E70013", secondary: "#FFFFFF", text: "#FFFFFF" },
  ALG: { primary: "#006233", secondary: "#FFFFFF", text: "#FFFFFF" },
  QAT: { primary: "#8D1B3D", secondary: "#FFFFFF", text: "#FFFFFF" },
  IRQ: { primary: "#000000", secondary: "#CE1126", text: "#FFFFFF" },
  JOR: { primary: "#000000", secondary: "#FFFFFF", text: "#FFFFFF" },
  UZB: { primary: "#0099B5", secondary: "#FFFFFF", text: "#FFFFFF" },
  COD: { primary: "#007FFF", secondary: "#F7D117", text: "#FFFFFF" },
  PAN: { primary: "#005293", secondary: "#D21034", text: "#FFFFFF" },
  BIH: { primary: "#002395", secondary: "#FECB00", text: "#FFFFFF" },
  CUW: { primary: "#003893", secondary: "#FFFFFF", text: "#FFFFFF" },
  CPV: { primary: "#003893", secondary: "#FFFFFF", text: "#FFFFFF" },
  HAI: { primary: "#00209F", secondary: "#D21034", text: "#FFFFFF" },
  NOR: { primary: "#BA0C2F", secondary: "#00205B", text: "#FFFFFF" },
  NZL: { primary: "#FFFFFF", secondary: "#000000", text: "#000000" },
  SWE: { primary: "#006AA7", secondary: "#FECC00", text: "#FFFFFF" },
  KSA: { primary: "#006C35", secondary: "#FFFFFF", text: "#FFFFFF" },
  ECU: { primary: "#FFD200", secondary: "#213470", text: "#000000" },
  RSA: { primary: "#007A4D", secondary: "#FECB00", text: "#FFFFFF" },
  CZE: { primary: "#11457E", secondary: "#D7141A", text: "#FFFFFF" },
  PAR: { primary: "#D52B1E", secondary: "#0038A8", text: "#FFFFFF" },
  IRN: { primary: "#239F40", secondary: "#DA0000", text: "#FFFFFF" },
  SCO: { primary: "#005EB8", secondary: "#FFFFFF", text: "#FFFFFF" },
};

export const getFlagUrl = (code: string) => {
  // Mapping some codes if they differ from ISO
  const map: Record<string, string> = {
    GER: "de",
    BRA: "br",
    ARG: "ar",
    COL: "co",
    MEX: "mx",
    USA: "us",
    CAN: "ca",
    URU: "uy",
    FRA: "fr",
    ESP: "es",
    ENG: "gb-eng",
    ITA: "it",
    NED: "nl",
    POR: "pt",
    BEL: "be",
    CRO: "hr",
    MAR: "ma",
    JPN: "jp",
    SEN: "sn",
    KOR: "kr",
    AUS: "au",
    SUI: "ch",
    TUR: "tr",
    AUT: "at",
    EGY: "eg",
    CIV: "ci",
    GHA: "gh",
    TUN: "tn",
    ALG: "dz",
    QAT: "qa",
    IRQ: "iq",
    JOR: "jo",
    UZB: "uz",
    COD: "cd",
    PAN: "pa",
    BIH: "ba",
    CUW: "cw",
    CPV: "cv",
    HAI: "ht",
    NOR: "no",
    NZL: "nz",
    SWE: "se",
    KSA: "sa",
    ECU: "ec",
    SCO: "gb-sct",
    RSA: "za",
    CZE: "cz",
    PAR: "py",
    IRN: "ir",
  };
  const iso = map[code] || code.toLowerCase();
  return `https://flagcdn.com/w160/${iso}.png`;
};
