export const PLAYER_NAMES: Record<string, Record<number, string>> = {
  MEX: {
    1: "MEX Escudo",
    2: "Luis Malagón",
    3: "Johan Vasquez",
    4: "Jorge Sánchez",
    5: "Cesar Montes",
    6: "Jesus Gallardo",
    7: "Israel Reyes",
    8: "Diego Lainez",
    9: "Carlos Rodriguez",
    10: "Edson Alvarez",
    11: "Orbelin Pineda",
    12: "Marcel Ruiz",
    13: "MEX Equipo",
    14: "Érick Sánchez",
    15: "Hirving Lozano",
    16: "Santiago Giménez",
    17: "Raúl Jiménez",
    18: "Alexis Vega",
    19: "Roberto Alvarado",
    20: "Cesar Huerta",
  },
  RSA: {
    1: "RSA Escudo",
    2: "Ronwen Williams",
    3: "Sipho Chaine",
    4: "Aubrey Modiba",
    5: "Samukele Kabini",
    6: "Mbekezeli Mbokazi",
    7: "Khulumani Ndamane",
    8: "Siyabonga Ngezana",
    9: "Khuliso Mudau",
    10: "Nkosinathi Sibisi",
    11: "Teboho Mokoena",
    12: "Thalente Mbatha",
    13: "RSA Equipo",
    14: "Bathasi Aubaas",
    15: "Yaya Sithole",
    16: "Sipho Mbule",
    17: "Lyle Foster",
    18: "Iqraam Rayners",
    19: "Mohau Nkota",
    20: "Oswin Appollis",
  },
  KOR: {
    1: "KOR Escudo",
    2: "Hyeon-woo Jo",
    3: "Seung-Gyu Kim",
    4: "Min-jae Kim",
    5: "Yu-min Cho",
    6: "Young-woo Seol",
    7: "Han-beom Lee",
    8: "Tae-seok Lee",
    9: "Myung-jae Lee",
    10: "Jae-sung Lee",
    11: "In-beom Hwang",
    12: "Kang-in Lee",
    13: "KOR Equipo",
    14: "Seung-ho Paik",
    15: "Jens Castrop",
    16: "Dong-yeong Lee",
    17: "Gue-sung Cho",
    18: "Heung-min Son",
    19: "Hee-chan Hwang",
    20: "Hyeon-Gyu Oh",
  },
  CZE: {
    1: "CZE Escudo",
    2: "Matej Kovar",
    3: "Jindrich Stanek",
    4: "Ladislav Krejci",
    5: "Vladimir Coufal",
    6: "Jaroslav Zeleny",
    7: "Tomas Holes",
    8: "David Zima",
    9: "Michal Sadilek",
    10: "Lukas Provod",
    11: "Lukas Cerv",
    12: "Tomas Soucek",
    13: "CZE Equipo",
    14: "Pavel Sulc",
    15: "Matej Vydra",
    16: "Vasil Kusej",
    17: "Tomas Chory",
    18: "Vaclav Cerny",
    19: "Adam Hlozek",
    20: "Patrik Schick",
  },
  CAN: {
    1: "CAN Escudo",
    2: "Dayne St.Clair",
    3: "Alphonso Davies",
    4: "Alistair Johnston",
    5: "Samuel Adekugbe",
    6: "Riche Larvea",
    7: "Derek Cornelius",
    8: "Moïse Bombito",
    9: "Kamal Miller",
    10: "Stephen Eustáquio",
    11: "Ismaël Koné",
    12: "Jonathan Osorio",
    13: "CAN Equipo",
    14: "Jacob Shaffelburg",
    15: "Mathieu Choinière",
    16: "Niko Sigur",
    17: "Tajon Buchanan",
    18: "Liam Millar",
    19: "Cyle Larin",
    20: "Jonathan David",
  },
  BIH: {
    1: "BIH Escudo",
    2: "Nikola Vasilj",
    3: "Amer Dedic",
    4: "Sead Kolasinac",
    5: "Tarik Muharemovic",
    6: "Nihad Mujakic",
    7: "Nikola Katic",
    8: "Amir Hadziahmetovic",
    9: "Benjamin Tahirovic",
    10: "Armin Gigovic",
    11: "Ivan Sunjic",
    12: "Ivan Basic",
    13: "BIH Equipo",
    14: "Dzenis Burnic",
    15: "Esmir Bajraktarevic",
    16: "Amar Memic",
    17: "Ermedin Demirovic",
    18: "Edin Dzeko",
    19: "Samed Bazdar",
    20: "Haris Tabakovic",
  },
  QAT: {
    1: "QAT Escudo",
    2: "Meshaal Barsham",
    3: "Sultan Albrake",
    4: "Lucas Mendes",
    5: "Homam Ahmed",
    6: "Boualem Khoukhi",
    7: "Pedro Miguel",
    8: "Tarek Salman",
    9: "Mohamed Al-Mannai",
    10: "Karim Boudiaf",
    11: "Assim Madibo",
    12: "Ahmed Fatehi",
    13: "QAT Equipo",
    14: "Mohammed Waad",
    15: "Abdulaziz Hatem",
    16: "Hassan Al-Haydos",
    17: "Edmilson Junior",
    18: "Akram Hassan Afif",
    19: "Ahmed Al Ganehi",
    20: "Almoez Ali",
  },
  SUI: {
    1: "SUI Escudo",
    2: "Gregor Kobel",
    3: "Yvon Mvogo",
    4: "Manuel Akanji",
    5: "Ricardo Rodriguez",
    6: "Nico Elvedi",
    7: "Aurèle Amenda",
    8: "Silvan Widmer",
    9: "Granit Xhaka",
    10: "Denis Zakaria",
    11: "Remo Freuler",
    12: "Fabian Rieder",
    13: "SUI Equipo",
    14: "Ardon Jashari",
    15: "Johan Manzambi",
    16: "Michel Aebischer",
    17: "Breel Embolo",
    18: "Ruben Vargas",
    19: "Dan Ndoye",
    20: "Zeki Amdouni",
  },
  BRA: {
    1: "BRA Escudo",
    2: "Alisson",
    3: "Bento",
    4: "Marquinhos",
    5: "Éder Militão",
    6: "Gabriel Magalhães",
    7: "Danilo",
    8: "Wesley",
    9: "Lucas Paquetá",
    10: "Casemiro",
    11: "Bruno Guimarães",
    12: "Luiz Henrique",
    13: "BRA Equipo",
    14: "Vinicius Júnior",
    15: "Rodrygo",
    16: "João Pedro",
    17: "Matheus Cunha",
    18: "Gabriel Martinelli",
    19: "Raphinha",
    20: "Estévão",
  },
  MAR: {
    1: "MAR Escudo",
    2: "Yassine Bounou",
    3: "Munir El Kajoui",
    4: "Achraf Hakimi",
    5: "Noussair Mazraoui",
    6: "Nayef Aguerd",
    7: "Roman Saiss",
    8: "Jawad El Yamio",
    9: "Adam Masina",
    10: "Sofyan Amrabat",
    11: "Azzedine Ounahi",
    12: "Eliesse Ben Seghir",
    13: "MAR Equipo",
    14: "Bilal El Khannouss",
    15: "Ismael Saibari",
    16: "Youssef En-Nesyri",
    17: "Abde Ezzalzouli",
    18: "Soufiane Rahimi",
    19: "Brahim Diaz",
    20: "Ayoub El Kaabi",
  },
  HAI: {
    1: "HAI Escudo",
    2: "Johny Placide",
    3: "Carlens Arcus",
    4: "Martin Expérience",
    5: "Jean-Kevin Duverne",
    6: "Ricardo Adé",
    7: "Duke Lacroix",
    8: "Garven Metusala",
    9: "Hannes Delcroix",
    10: "Leverton Pierre",
    11: "Danley Jean Jacques",
    12: "Jean-Ricner Bellegarde",
    13: "HAI Equipo",
    14: "Christopher Attys",
    15: "Derrick Etienne Jr",
    16: "Josue Casimir",
    17: "Ruben Providence",
    18: "Duckens Nazon",
    19: "Louicius Deedson",
    20: "Frantzdy Pierrot",
  },
  SCO: {
    1: "SCO Escudo",
    2: "Angus Gunn",
    3: "Jack Hendry",
    4: "Kieran Tierney",
    5: "Aaron Hickey",
    6: "Andrew Robertson",
    7: "Scott McKenna",
    8: "John Souttar",
    9: "Anthony Ralston",
    10: "Grant Hanley",
    11: "Scott McTominay",
    12: "Billy Gilmour",
    13: "SCO Equipo",
    14: "Lewis Ferguson",
    15: "Ryan Christie",
    16: "Kenny McLean",
    17: "John McGinn",
    18: "Lyndon Dykes",
    19: "Che Adams",
    20: "Ben Gannon-Doak",
  },
  USA: {
    1: "USA Escudo",
    2: "Math Freese",
    3: "Chris Richards",
    4: "Tim Ream",
    5: "Mark McKenzie",
    6: "Alex Freeman",
    7: "Antonee Robinson",
    8: "Tyler Adams",
    9: "Tanner Tessmann",
    10: "Weston McKenny",
    11: "Christian Roldan",
    12: "Timothy Weah",
    13: "USA Equipo",
    14: "Diego Luna",
    15: "Malik Tillman",
    16: "Christian Pulisic",
    17: "Brenden Aaronson",
    18: "Ricardo Pepi",
    19: "Haji Wright",
    20: "Folarin Balogun",
  },
  PAR: {
    1: "PAR Escudo",
    2: "Roberto Fernandez",
    3: "Orlando Gill",
    4: "Gustavo Gomez",
    5: "Fabián Balbuena",
    6: "Juan José Cáceres",
    7: "Omar Alderete",
    8: "Junior Alonso",
    9: "Mathías Villasanti",
    10: "Diego Gomez",
    11: "Damián Bobadilla",
    12: "Andres Cubas",
    13: "PAR Equipo",
    14: "Matias Galarza Fonda",
    15: "Julio Enciso",
    16: "Alejandro Romero Gamarra",
    17: "Miguel Almirón",
    18: "Ramon Sosa",
    19: "Angel Romero",
    20: "Antonio Sanabria",
  },
  AUS: {
    1: "AUS Escudo",
    2: "Mathew Ryan",
    3: "Joe Gauci",
    4: "Harry Souttar",
    5: "Alessandro Circati",
    6: "Jordan Bos",
    7: "Aziz Behich",
    8: "Cameron Burgess",
    9: "Lewis Miller",
    10: "Milos Degenek",
    11: "Jackson Irvine",
    12: "Riley McGree",
    13: "AUS Equipo",
    14: "Aiden O'Neill",
    15: "Connor Metcalfe",
    16: "Patrick Yazbek",
    17: "Craig Goodwin",
    18: "Kusini Vengi",
    19: "Nestory Irankunda",
    20: "Mohamed Touré",
  },
  TUR: {
    1: "TUR Escudo",
    2: "Ugurcan Cakir",
    3: "Mert Muldur",
    4: "Zeki Celik",
    5: "Abdulkerim Bardakci",
    6: "Caglar Soyuncu",
    7: "Merih Demiral",
    8: "Ferdi Kadioglu",
    9: "Kaan Ayhan",
    10: "Ismail Yuksek",
    11: "Hakan Calhanoglu",
    12: "Orkun Kokcu",
    13: "TUR Equipo",
    14: "Arda Guler",
    15: "Irfan Can Kahveci",
    16: "Yunus Akgun",
    17: "Can Uzun",
    18: "Baris Alper Yilmaz",
    19: "Kerem Akturkoglu",
    20: "Kenan Yildiz",
  },
  GER: {
    1: "GER Escudo",
    2: "Marc-André ter Stegen",
    3: "Jonathan Tah",
    4: "David Raum",
    5: "Nico Schlotterbeck",
    6: "Antonio Rüdiger",
    7: "Waldemar Anton",
    8: "Ridle Baku",
    9: "Maximilian Mittelstadt",
    10: "Joshua Kimmich",
    11: "Florian Wirtz",
    12: "Felix Nmecha",
    13: "GER Equipo",
    14: "Leon Goretzka",
    15: "Jamal Musiala",
    16: "Serge Gnabry",
    17: "Kai Havertz",
    18: "Leroy Sane",
    19: "Karim Adeyemi",
    20: "Nick Woltemade",
  },
  CUW: {
    1: "CUW Escudo",
    2: "Eloy Room",
    3: "Armando Obispo",
    4: "Sherel Floranus",
    5: "Jurien Gaari",
    6: "Joshua Brenet",
    7: "Roshon Van Eijma",
    8: "Shurandy Sambo",
    9: "Livano Comenencia",
    10: "Godfried Roemeratoe",
    11: "Juninho Bacuna",
    12: "Leandro Bacuna",
    13: "CUW Equipo",
    14: "Tahith Chong",
    15: "Kenji Gorre",
    16: "Jearl Margaritha",
    17: "Jurgen Locadia",
    18: "Jeremy Antonisse",
    19: "Gervane Kastaneer",
    20: "Sontje Hansen",
  },
  CIV: {
    1: "CIV Escudo",
    2: "Yahia Fofana",
    3: "Ghislain Konan",
    4: "Wilfried Singo",
    5: "Odilon Kossounou",
    6: "Evan Ndicka",
    7: "Willy Boly",
    8: "Emmanuel Agbadou",
    9: "Ousmane Diomande",
    10: "Franck Kessie",
    11: "Seko Fofana",
    12: "Ibrahim Sangare",
    13: "CIV Equipo",
    14: "Jean-Philippe Gbamin",
    15: "Amad Diallo",
    16: "Sébastien Haller",
    17: "Simon Adingra",
    18: "Yan Diomande",
    19: "Evann Guessand",
    20: "Oumar Diakite",
  },
  ECU: {
    1: "ECU Escudo",
    2: "Hernán Galíndez",
    3: "Gonzalo Valle",
    4: "Piero Hincapié",
    5: "Pervis Estupiñán",
    6: "Willian Pacho",
    7: "Ángelo Preciado",
    8: "Joel Ordóñez",
    9: "Moises Caicedo",
    10: "Alan Franco",
    11: "Kendry Paez",
    12: "Pedro Vite",
    13: "ECU Equipo",
    14: "John Veboah",
    15: "Leonardo Campana",
    16: "Gonzalo Plata",
    17: "Nilson Angulo",
    18: "Alan Minda",
    19: "Kevin Rodriguez",
    20: "Enner Valencia",
  },
  NED: {
    1: "NED Escudo",
    2: "Bart Verbruggen",
    3: "Virgil van Dijk",
    4: "Micky van de Ven",
    5: "Jurrien Timber",
    6: "Denzel Dumfries",
    7: "Nathan Aké",
    8: "Jeremie Frimpong",
    9: "Jan Paul van Hecke",
    10: "Tijjani Reijnders",
    11: "Ryan Gravenberch",
    12: "Teun Koopmeiners",
    13: "NED Equipo",
    14: "Frenkie de Jong",
    15: "Xavi Simons",
    16: "Justin Kluivert",
    17: "Memphis Depay",
    18: "Donyell Malen",
    19: "Wout Weghorst",
    20: "Cody Gakpo",
  },
  JPN: {
    1: "JPN Escudo",
    2: "Zion Suzuki",
    3: "Henry Heroki Mochizuki",
    4: "Ayumu Seko",
    5: "Junnosuke Suzuki",
    6: "Shogo Taniguchi",
    7: "Tsuyoshi Watanabe",
    8: "Kaishu Sano",
    9: "Yuki Soma",
    10: "Ao Tanaka",
    11: "Daichi Kamada",
    12: "Takefusa Kubo",
    13: "JPN Equipo",
    14: "Ritsu Doan",
    15: "Keito Nakamura",
    16: "Takumi Minamino",
    17: "Shuto Machino",
    18: "Junya Ito",
    19: "Koki Ogawa",
    20: "Ayase Ueda",
  },
  SWE: {
    1: "SWE Escudo",
    2: "Victor Johansson",
    3: "Isak Hien",
    4: "Gabriel Gudmundsson",
    5: "Emil Holm",
    6: "Victor Nilsson Lindelöf",
    7: "Gustaf Lagerbielke",
    8: "Lucas Bergvall",
    9: "Hugo Larsson",
    10: "Jesper Karlström",
    11: "Yasin Ayari",
    12: "Mattias Svanberg",
    13: "SWE Equipo",
    14: "Daniel Svensson",
    15: "Ken Sema",
    16: "Roony Bardghji",
    17: "Dejan Kulusevski",
    18: "Anthony Elanga",
    19: "Alexander Isak",
    20: "Viktor Gyökeres",
  },
  TUN: {
    1: "TUN Escudo",
    2: "Bechir Ben Said",
    3: "Aymen Dahmen",
    4: "Yan Valery",
    5: "Montassar Talbi",
    6: "Yassine Meriah",
    7: "Ali Abdi",
    8: "Dylan Bronn",
    9: "Ellyes Skhiri",
    10: "Aissa Laidouni",
    11: "Ferjani Sassi",
    12: "Mohamed Ali Ben Romdhane",
    13: "TUN Equipo",
    14: "Hannibal Mejbri",
    15: "Elias Achouri",
    16: "Elias Saad",
    17: "Hazem Mastouri",
    18: "Ismael Gharbi",
    19: "Sayfallah Ltaief",
    20: "Naim Sliti",
  },
  BEL: {
    1: "BEL Escudo",
    2: "Thibaut Courtois",
    3: "Arthur Theate",
    4: "Timothy Castagne",
    5: "Zeno Debast",
    6: "Brandon Mechele",
    7: "Maxim De Cuyper",
    8: "Thomas Meunier",
    9: "Youri Tielemans",
    10: "Amadou Onana",
    11: "Nicolas Raskin",
    12: "Alexis Saelemaekers",
    13: "BEL Equipo",
    14: "Hans Vanaken",
    15: "Kevin De Bruyne",
    16: "Jérémy Doku",
    17: "Charles De Ketelaere",
    18: "Leandro Trossard",
    19: "Loïs Openda",
    20: "Romelu Lukaku",
  },
  EGY: {
    1: "EGY Escudo",
    2: "Mohamed El Shenawy",
    3: "Mohamed Hany",
    4: "Mohamed Hamdy",
    5: "Yasser Ibrahim",
    6: "Khaled Sobhi",
    7: "Ramy Rabia",
    8: "Hossam Abdelmaguid",
    9: "Ahmed Fatouh",
    10: "Marwan Attia",
    11: "Zizo",
    12: "Hamdy Fathy",
    13: "EGY Equipo",
    14: "Mohamed Lasheen",
    15: "Emam Ashour",
    16: "Osama Faisal",
    17: "Mohamed Salah",
    18: "Mostafa Mohamed",
    19: "Trezeguet",
    20: "Omar Marmoush",
  },
  IRN: {
    1: "IRN Escudo",
    2: "Alireza Beiranvand",
    3: "Morteza Pouraliganji",
    4: "Ehsan Hajsafi",
    5: "Milad Mohammadi",
    6: "Shojae Khalilzadeh",
    7: "Ramin Rezaeian",
    8: "Hossein Kanaani",
    9: "Sadegh Moharrami",
    10: "Saleh Hardani",
    11: "Saeed Ezatolahi",
    12: "Saman Ghoddos",
    13: "IRN Equipo",
    14: "Omid Noorafkan",
    15: "Roozbeh Cheshmi",
    16: "Mohammad Mohebi",
    17: "Sardar Azmoun",
    18: "Mehdi Taremi",
    19: "Alireza Jahanbakhsh",
    20: "Ali Gholizadeh",
  },
  NZL: {
    1: "NZL Escudo",
    2: "Max Crocombe Payne",
    3: "Alex Paulsen",
    4: "Michael Boxall",
    5: "Liberato Cacace",
    6: "Tim Payne",
    7: "Tyler Bindon",
    8: "Francis de Vries",
    9: "Finn Surman",
    10: "Joe Bell",
    11: "Sarpreet Singh",
    12: "Ryan Thomas",
    13: "NZL Equipo",
    14: "Matthew Garbett",
    15: "Marko Stamenić",
    16: "Ben Old",
    17: "Chris Wood",
    18: "Elijah Just",
    19: "Callum McCowatt",
    20: "Kosta Barbarouses",
  },
  ESP: {
    1: "ESP Escudo",
    2: "Unai Simon",
    3: "Robin Le Normand",
    4: "Aymeric Laporte",
    5: "Dean Huijsen",
    6: "Pedro Porro",
    7: "Dani Carvajal",
    8: "Marc Cucurella",
    9: "Martín Zubimendi",
    10: "Rodri",
    11: "Pedri",
    12: "Fabian Ruiz",
    13: "ESP Equipo",
    14: "Mikel Merino",
    15: "Lamine Yamal",
    16: "Dani Olmo",
    17: "Nico Williams",
    18: "Ferran Torres",
    19: "Álvaro Morata",
    20: "Mikel Oyarzabal",
  },
  CPV: {
    1: "CPV Escudo",
    2: "Vozinha",
    3: "Logan Costa",
    4: "Pico",
    5: "Diney",
    6: "Steven Moreira",
    7: "Wagner Pina",
    8: "Joao Paulo",
    9: "Yannick Semedo",
    10: "Kevin Pina",
    11: "Patrick Andrade",
    12: "Jamiro Monteiro",
    13: "CPV Equipo",
    14: "Deroy Duarte",
    15: "Garry Rodrigues",
    16: "Jovane Cabral",
    17: "Ryan Mendes",
    18: "Dailon Livramento",
    19: "Willy Semedo",
    20: "Bebe",
  },
  KSA: {
    1: "KSA Escudo",
    2: "Nawaf Alaqidi",
    3: "Abdulrahman Al-Sanbi",
    4: "Saud Abdulhamid",
    5: "Nawaf Bouwashl",
    6: "Jihad Thakri",
    7: "Moteb Al-Harbi",
    8: "Hassan Altambakti",
    9: "Musab Aljuwayr",
    10: "Ziyad Aljohani",
    11: "Abdullah Alkhaibari",
    12: "Nasser Aldawsari",
    13: "KSA Equipo",
    14: "Saleh Abu Alshamat",
    15: "Marwan Alsahafi",
    16: "Salem Aldawsari",
    17: "Abdulrahman Al-Aboud",
    18: "Feras Akbrikan",
    19: "Saleh Alshehri",
    20: "Abdullah Al-Hamdan",
  },
  URU: {
    1: "URU Escudo",
    2: "Sergio Rochet",
    3: "Santiago Mele",
    4: "Ronald Araujo",
    5: "José María Giménez",
    6: "Sebastian Caceres",
    7: "Mathias Olivera",
    8: "Guillermo Varela",
    9: "Nahitan Nandez",
    10: "Federico Valverde",
    11: "Giorgian De Arrascaeta",
    12: "Rodrigo Bentancur",
    13: "URU Equipo",
    14: "Manuel Ugarte",
    15: "Nicolás de la Cruz",
    16: "Maxi Araujo",
    17: "Darwin Núñez",
    18: "Federico Viñas",
    19: "Rodrigo Aguirre",
    20: "Facundo Pellistri",
  },
  FRA: {
    1: "FRA Escudo",
    2: "Mike Maignan",
    3: "Theo Hernandez",
    4: "William Saliba",
    5: "Jules Kounde",
    6: "Ibrahima Konate",
    7: "Dayot Upamecano",
    8: "Lucas Digne",
    9: "Aurélien Tchouaméni",
    10: "Eduardo Camavinga",
    11: "Manu Kone",
    12: "Adrien Rabiot",
    13: "FRA Equipo",
    14: "Michael Olise",
    15: "Ousmane Dembele",
    16: "Bradley Barcola",
    17: "Désiré Doué",
    18: "Kingsley Coman",
    19: "Hugo Ekitike",
    20: "Kylian Mbappe",
  },
  SEN: {
    1: "SEN Escudo",
    2: "Edouard Mendy",
    3: "Yehvann Diouf",
    4: "Moussa Niakhaté",
    5: "Abdoulaye Seck",
    6: "Ismail Jakobs",
    7: "El Hadji Malick Diouf",
    8: "Kalidou Koulibaly",
    9: "Idrissa Gana Gueye",
    10: "Pape Matar Sarr",
    11: "Pape Gueye",
    12: "Habib Diarra",
    13: "SEN Equipo",
    14: "Lamine Camara",
    15: "Sadio Mane",
    16: "Ismaïla Sarr",
    17: "Boulaye Dia",
    18: "Iliman Ndiaye",
    19: "Nicolas Jackson",
    20: "Krepin Diatta",
  },
  IRQ: {
    1: "IRQ Escudo",
    2: "Jalal Hassan",
    3: "Rebin Sulaka",
    4: "Hussein Ali",
    5: "Akam Hashem",
    6: "Merchas Doski",
    7: "Zaid Tahseen",
    8: "Manaf Younis",
    9: "Zidane Iqbal",
    10: "Amir Al-Ammari",
    11: "Ibrahim Bavesh",
    12: "Ali Jasim",
    13: "IRQ Equipo",
    14: "Youssef Amyn",
    15: "Aimar Sher",
    16: "Marko Farji",
    17: "Osama Rashid",
    18: "Ali Al-Hamadi",
    19: "Aymen Hussein",
    20: "Mohanad Ali",
  },
  NOR: {
    1: "NOR Escudo",
    2: "Orjan Nyland",
    3: "Julian Ryerson",
    4: "Leo Ostigård",
    5: "Kristoffer Vassbakk Ajer",
    6: "Marcus Holmgren Pedersen",
    7: "David Møller Wolfe",
    8: "Torbjørn Heggem",
    9: "Morten Thorsby",
    10: "Martin Ødegaard",
    11: "Sander Berge",
    12: "Andreas Schjelderup",
    13: "NOR Equipo",
    14: "Patrick Berg",
    15: "Erling Haaland",
    16: "Alexander Sørloth",
    17: "Aron Dønnum",
    18: "Jorgen Strand Larsen",
    19: "Antonio Nusa",
    20: "Oscar Bobb",
  },
  ARG: {
    1: "ARG Escudo",
    2: "Emiliano Martinez",
    3: "Nahuel Molina",
    4: "Cristian Romero",
    5: "Nicolas Otamendi",
    6: "Nicolas Tagliafico",
    7: "Leonardo Balerdi",
    8: "Enzo Fernandez",
    9: "Alexis Mac Allister",
    10: "Rodrigo De Paul",
    11: "Exequiel Palacios",
    12: "Leandro Paredes",
    13: "ARG Equipo",
    14: "Nico Paz",
    15: "Franco Mastantuono",
    16: "Nico Gonzalez",
    17: "Lionel Messi",
    18: "Lautaro Martinez",
    19: "Julian Alvarez",
    20: "Giuliano Simeone",
  },
  ALG: {
    1: "ALG Escudo",
    2: "Alexis Guendouz",
    3: "Ramy Bensebaini",
    4: "Youcef Atal",
    5: "Rayan Aït-Nouri",
    6: "Mohamed Amine Tougai",
    7: "Aïssa Mandi",
    8: "Ismael Bennacer",
    9: "Houssem Aquar",
    10: "Hicham Boudaoui",
    11: "Ramiz Zerrouki",
    12: "Nabil Bentalab",
    13: "ALG Equipo",
    14: "Farés Chaibi",
    15: "Riyad Mahrez",
    16: "Said Benrahma",
    17: "Anis Hadj Moussa",
    18: "Amine Gouiri",
    19: "Baghdad Bounedjah",
    20: "Mohammed Amoura",
  },
  AUT: {
    1: "AUT Escudo",
    2: "Alexander Schlager",
    3: "Patrick Pentz",
    4: "David Alaba",
    5: "Kevin Danso",
    6: "Philipp Lienhart",
    7: "Stefan Posch",
    8: "Phillipp Mwene",
    9: "Alexander Prass",
    10: "Xaver Schlager",
    11: "Marcel Sabitzer",
    12: "Konrad Laimer",
    13: "AUT Equipo",
    14: "Florian Grillitsch",
    15: "Nicolas Seiwald",
    16: "Romano Schmid",
    17: "Patrick Wimmer",
    18: "Christoph Baumgartner",
    19: "Michael Gregoritsch",
    20: "Marko Arnautović",
  },
  JOR: {
    1: "JOR Escudo",
    2: "Yazeed Abulaila",
    3: "Ihsan Haddad",
    4: "Mohammad Abu Hashish",
    5: "Yazan Al-Arab",
    6: "Abdallah Nasib",
    7: "Saleem Obaid",
    8: "Mohammad Abualnadi",
    9: "Ibrahim Saadeh",
    10: "Nizar Al-Rashdan",
    11: "Noor Al-Rawabdeh",
    12: "Mohannad Abu Taha",
    13: "JOR Equipo",
    14: "Amer Jamous",
    15: "Musa Al-Taamari",
    16: "Yazan Al-Naimat",
    17: "Mahmoud Al-Mardi",
    18: "Ali Olwan",
    19: "Mohammad Abu Zrayq",
    20: "Ibrahim Sabra",
  },
  POR: {
    1: "POR Escudo",
    2: "Diogo Costa",
    3: "Jose Sa",
    4: "Ruben Dias",
    5: "João Cancelo",
    6: "Diogo Dalot",
    7: "Nuno Mendes",
    8: "Gonçalo Inácio",
    9: "Bernardo Silva",
    10: "Bruno Fernandes",
    11: "Ruben Neves",
    12: "Vitinha",
    13: "POR Equipo",
    14: "João Neves",
    15: "Cristiano Ronaldo",
    16: "Francisco Trincao",
    17: "João Felix",
    18: "Gonçalo Ramos",
    19: "Pedro Neto",
    20: "Rafael Leão",
  },
  COD: {
    1: "COD Escudo",
    2: "Lionel Mpasi",
    3: "Aaron Wan-Bissaka",
    4: "Axel Tuanzebe",
    5: "Arthur Masuaku",
    6: "Chancel Mbemba",
    7: "Joris Kayembe",
    8: "Charles Pickel",
    9: "Ngal'ayel Mukau",
    10: "Edo Kayembe",
    11: "Samuel Moutoussamy",
    12: "Noah Sadiki",
    13: "COD Equipo",
    14: "Théo Bongonda",
    15: "Meschak Elia",
    16: "Yoane Wissa",
    17: "Brian Cipenga",
    18: "Fiston Mayele",
    19: "Cédric Bakambu",
    20: "Nathanaël Mbuku",
  },
  UZB: {
    1: "UZB Escudo",
    2: "Utkir Yusupov",
    3: "Farrukh Savfiev",
    4: "Sherzod Nasrullaev",
    5: "Umar Eshmurodov",
    6: "Husniddin Aliqulov",
    7: "Rustamjon Ashurmatov",
    8: "Khojiakbar Alijonov",
    9: "Abdukodir Khusanov",
    10: "Odiljon Hamrobekov",
    11: "Otabek Shukurov",
    12: "Jamshid Iskanderov",
    13: "UZB Equipo",
    14: "Azizbek Turgunboev",
    15: "Khojimat Erkinov",
    16: "Eldor Shomurodov",
    17: "Oston Urunov",
    18: "Jaloliddin Masharipov",
    19: "Igor Sergeev",
    20: "Abbosbek Fayzullaev",
  },
  COL: {
    1: "COL Escudo",
    2: "Camilo Vargas",
    3: "David Ospina",
    4: "Dávinson Sánchez",
    5: "Yerry Mina",
    6: "Daniel Munoz",
    7: "Johan Mojica",
    8: "Jhon Lucumí",
    9: "Santiago Arias",
    10: "Jefferson Lerma",
    11: "Kevin Castaño",
    12: "Richard Rios",
    13: "COL Equipo",
    14: "James Rodriguez",
    15: "Juan Fernando Quintero",
    16: "Jorge Carrascal",
    17: "Jon Arias",
    18: "Jhon Cordova",
    19: "Luis Suarez",
    20: "Luis Diaz",
  },
  ENG: {
    1: "ENG Escudo",
    2: "Jordan Pickford",
    3: "John Stones",
    4: "Marc Guéhi",
    5: "Ezri Konsa",
    6: "Trent Alexander-Arnold",
    7: "Reece James",
    8: "Dan Burn",
    9: "Jordan Henderson",
    10: "Declan Rice",
    11: "Jude Bellingham",
    12: "Cole Palmer",
    13: "ENG Equipo",
    14: "Morgan Rogers",
    15: "Anthony Gordon",
    16: "Phil Foden",
    17: "Bukayo Saka",
    18: "Harry Kane",
    19: "Marcus Rashford",
    20: "Ollie Watkins",
  },
  CRO: {
    1: "CRO Escudo",
    2: "Dominik Livaković",
    3: "Duje Caleta-Car",
    4: "Josko Gvardiol",
    5: "Josip Stanišić",
    6: "Luka Vušković",
    7: "Josip Sutalo",
    8: "Kristijan Jakic",
    9: "Luka Modrić",
    10: "Mateo Kovacic",
    11: "Martin Baturina",
    12: "Lovro Majer",
    13: "CRO Equipo",
    14: "Mario Pasalic",
    15: "Petar Sucic",
    16: "Ivan Perišić",
    17: "Marco Pasalic",
    18: "Ante Budimir",
    19: "Andrej Kramarić",
    20: "Franjo Ivanovic",
  },
  GHA: {
    1: "GHA Escudo",
    2: "Lawrence Ati Zigi",
    3: "Tariq Lamptey",
    4: "Mohammed Salisu",
    5: "Alidu Seidu",
    6: "Alexander Djiku",
    7: "Gideon Mensah",
    8: "Caleb Yirenkyi",
    9: "Abdul Issahaku Fatawu",
    10: "Thomas Partey",
    11: "Salis Abdul Samed",
    12: "Kamaldeen Sulemana",
    13: "GHA Equipo",
    14: "Mohammed Kudus",
    15: "Inaki Williams",
    16: "Jordan Ayew",
    17: "Andrew Ayew",
    18: "Joseph Paintsil",
    19: "Osman Bukari",
    20: "Antoine Semenyo",
  },
  PAN: {
    1: "PAN Escudo",
    2: "Orlando Mosquera",
    3: "Luis Mejia",
    4: "Fidel Escobar",
    5: "Andres Andrade",
    6: "Michael Amir Murillo",
    7: "Eric Davis",
    8: "Jose Cordoba",
    9: "Cesar Blackman",
    10: "Cristian Martinez",
    11: "Aníbal Godoy",
    12: "Adalberto Carrasquilla",
    13: "PAN Equipo",
    14: "Édgar Bárcenas",
    15: "Carlos Harvey",
    16: "Ismael Díaz",
    17: "Jose Fajardo",
    18: "Cecilio Waterman",
    19: "Jose Luiz Rodriguez",
    20: "Alberto Quintero",
  },
};
